application: task-pad
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon    

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /cleanup
  script: website.py
  login: admin

- url: .*
  script: website.py